### ISSUE TITLE
Why shouldn't be the admin replication controller scaled past 1?

### ISSUE THREAD

**Issue by FilipVozar** [couchbase/kubernetes#36]
Since the admin and node pods differ only in labels,
the only reason I could come up with is that I hit
only one pod when accessing web UI, but with Couchbase
it doesn't matter which node I connect to as long as
it's part of the cluster, right?

If I never wanted to use the web UI (or very rarely),
is it safe to scale admin replication controller to 0 pods
and only use the "basic" node replication controller
for running the cluster?

**Comment by tleyden** [comment]
> but with Couchbase it doesn't matter which node I connect to as long as it's part of the cluster, right?

Correct

> If I never wanted to use the web UI (or very rarely), is it safe to scale admin replication controller to 0 pods and only use the "basic" node replication controller for running the cluster?

Yes, if you didn't want the web UI, you could set the admin replication controller to 0 and everything should still work (if not, please file an issue!).  

Even the web UI will work if you go directly to any of the basic nodes.  The instructions just treat the admin node special because it gets mapped to the publicly available load balanced address so it's easy for users to hit the web UI.

Going to close the ticket since there's no action items, but feel free to ask more questions on this ticket or open new tickets with any other questions.
