### ISSUE TITLE
Upgrading the cluster & appropriate sizing

### ISSUE THREAD

**Issue by derekperkins** [couchbase/kubernetes#6]
I'm trying to figure out the instance sizes to run and how many nodes to put in my cluster. I'm using it as a caching layer, so currently my reads and writes are about equal. I'm migrating from Google Cloud Datastore. This is what my workload has been averaging this month so far:
- Avg 150 Write Ops / sec
- Avg 150 Read Ops / sec
- Peak 750 Write Ops / sec
- Peak 750 Read Ops / sec
- Avg 4kb record size
- Peak 3 MB record size (rare)

Would it cause any issues to add a larger machine type to the cluster? Would that be the right way to go about increasing the capacity - adding larger machines to the cluster and then killing the smaller ones? Any advice you have would be very helpful.

I apologize if this is the wrong place to ask about this, but as I'm new to both GKE and Couchbase, this seems like the best spot.

PS. I ran the demo setup with an f1-micro rather than a g1-small. It's been an hour and all my pods listed for `kubectl get pods` are still pending, with the CPU pegged the entire time. I'll wait until they complete to see how long it takes, but it may be worth a warning in the readme.

**Comment by tleyden** [comment]
Can you ask this question here instead?  https://forums.couchbase.com/

I would say something like "I'm running on GKE and looking for sizing suggestions.  Since GKE is ultimately backed by GCE, any GCE guidance should apply".  The reason I say that is because our support staff is still not fully ramped up on GKE yet, and may be hesitant to make suggestions.

Post a link to your post on this ticket so we can cross link the issues.

**Comment by derekperkins** [comment]
Thanks for your help. Here's a link to the question.
https://forums.couchbase.com/t/cluster-size-recommendations-running-4-0-on-compute-engine/4206
